version: 2.1
test_build_filters: &test_build_filters
  branches:
    only: /.*/
  tags:
    ignore: /[0-9]+\.[0-9]+\.[0-9]+/
jobs:
  test:
    docker:
      - image: circleci/node:12.13.0
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
workflows:
  test:
    jobs:
      - test:
          filters: *test_build_filters
